### ISSUE TITLE
Plugin requires Java 8

### ISSUE THREAD

**Issue by mvysny** [TELL-SRL/gradle-sass#3]
Thank you very much for your wonderful work, the plugin works amazingly. However, the plugin does not work on Java 7:

> org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'lsps-doc'.
>         at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
>         at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:144)
>         at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
>         at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:149)
>         at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
>         at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
>         at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
>         at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
>         at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:510)
>         at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90)
>         at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
>         at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
>         at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
>         at org.gradle.internal.Factories$1.create(Factories.java:22)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
>         at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
>         at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
>         at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
>         at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
>         at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
>         at org.gradle.launcher.Main.doAction(Main.java:33)
>         at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
>         at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
>         at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
>         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
>         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: it/tellnet/gradle/SassPlugin : Unsupported major.minor version 52.0
>         at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
>         at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
>         at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
>         at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
>         at org.gradle.api.internal.plugins.DefaultPluginRegistry.uncheckedGet(DefaultPluginRegistry.java:149)
>         at org.gradle.api.internal.plugins.DefaultPluginRegistry.lookup(DefaultPluginRegistry.java:144)
>         at org.gradle.api.internal.plugins.DefaultPluginRegistry.lookup(DefaultPluginRegistry.java:127)
>         at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:108)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
>         at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
>         at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
>         at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
>         at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
>         at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
>         at build_ak99m085l9ru5j88uusls1neb.run(D:\LSPS\trunk\lsps-doc\build.gradle:18)
>         at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
>         ... 50 more
> Caused by: java.lang.UnsupportedClassVersionError: it/tellnet/gradle/SassPlugin : Unsupported major.minor version 52.0
>         at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:71)
>         at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:51)
>         at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
>         at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
>         at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
>         at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
>         ... 67 more

Could you please recompile and publish your plugin with Java 7? Thank you

**Comment by mvysny** [comment]
A solution is to force the java compiler to produce 1.7 classes: https://discuss.gradle.org/t/enforcing-targetcompatibility-when-compiling-java-code-with-the-groovy-plugin/5065
